"""
Generate a development fixture for the ARES dashboard.

    python make_fixture.py > backend/data/fixture_detections.json

WHY THIS EXISTS
    So the frontend can be built before real drone footage has been processed.
    Output shape matches the team's agreed contract exactly, so swapping in
    real detections later changes nothing in the dashboard code.

WHAT THIS IS NOT
    This is NOT demo data. These boxes are generated by arithmetic, not by the
    detection model. Never load this file for a demo, a screenshot, or the
    recorded video. Delete it once real detections exist.
"""

import json
import math
import random
import sys

SEED        = 7          # fixed so the fixture is reproducible
FRAMES      = 300        # 10 s at 30 fps
WIDTH       = 1280
HEIGHT      = 720
N_SURVIVORS = 9

random.seed(SEED)


def make_survivor(track_id: int, cluster: bool) -> dict:
    """One person: a start position, a drift direction, and a visible span."""
    if cluster:
        # A tight group — gives the priority scorer real cluster signal.
        cx = 880 + random.uniform(-45, 45)
        cy = 430 + random.uniform(-45, 45)
    else:
        cx = random.uniform(120, WIDTH - 120)
        cy = random.uniform(100, HEIGHT - 100)

    first = random.randint(0, 40)
    return {
        "track_id":   track_id,
        "x":          cx,
        "y":          cy,
        "dx":         random.uniform(-0.28, 0.28),   # px per frame — drone drift
        "dy":         random.uniform(-0.18, 0.18),
        "w":          random.uniform(26, 46),        # a person at ~20 m altitude
        "h":          random.uniform(48, 82),
        "base_conf":  random.uniform(0.34, 0.93),
        "first_seen": first,
        "last_seen":  min(FRAMES - 1, first + random.randint(150, FRAMES)),
    }


def main() -> None:
    survivors = [make_survivor(i + 1, cluster=(i >= N_SURVIVORS - 3))
                 for i in range(N_SURVIVORS)]

    detections = []

    for frame_id in range(FRAMES):
        for s in survivors:
            if not (s["first_seen"] <= frame_id <= s["last_seen"]):
                continue

            # Occasional dropout — a real detector misses frames.
            if random.random() < 0.06:
                continue

            t  = frame_id - s["first_seen"]
            cx = s["x"] + s["dx"] * t + math.sin(t / 22) * 3.5
            cy = s["y"] + s["dy"] * t + math.cos(t / 26) * 2.5

            x1 = max(0, cx - s["w"] / 2)
            y1 = max(0, cy - s["h"] / 2)
            x2 = min(WIDTH,  cx + s["w"] / 2)
            y2 = min(HEIGHT, cy + s["h"] / 2)

            conf = min(0.97, max(0.18, s["base_conf"] + random.uniform(-0.09, 0.09)))

            detections.append({
                "frame_id":   frame_id,
                "bbox":       [round(x1, 1), round(y1, 1), round(x2, 1), round(y2, 1)],
                "confidence": round(conf, 3),
                "track_id":   s["track_id"],
                "class":      0,
            })

        # A few untracked detections — the tracker does not always assign an ID.
        if random.random() < 0.10:
            x1 = random.uniform(0, WIDTH - 60)
            y1 = random.uniform(0, HEIGHT - 90)
            detections.append({
                "frame_id":   frame_id,
                "bbox":       [round(x1, 1), round(y1, 1),
                               round(x1 + 34, 1), round(y1 + 62, 1)],
                "confidence": round(random.uniform(0.18, 0.34), 3),
                "track_id":   -1,
                "class":      0,
            })

    detections.sort(key=lambda d: d["frame_id"])
    json.dump(detections, sys.stdout, indent=2)

    unique = len({d["track_id"] for d in detections if d["track_id"] != -1})
    print(f"\n[fixture] {len(detections)} detections · "
          f"{unique} unique tracks · {FRAMES} frames · {WIDTH}x{HEIGHT}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
